Add user agreements attribute to userfas
fedora-infra/freeipa-fas pull request #103
Opened 2020-05-12 09:58 UTC by ryanlerch

Related: fedora-infra/noggin#51

2020-05-12 12:49 UTC, Conan-Kudo commented
Question, why is this an attribute and not using groups? Most of our extensions and APIs assume that the user is a member of the group that signed the FPCA. Also, how would this extend to _multiple_ user agreements (e.g. code of conduct, then FPCA, etc.).

2020-05-12 12:57 UTC, tiran commented
> Question, why is this an attribute and not using groups? Most of our extensions and APIs assume that the user is a member of the group that signed the FPCA. Also, how would this extend to _multiple_ user agreements (e.g. code of conduct, then FPCA, etc.)?

It's a multi-valued string attribute. You can have multiple agreements.

2020-05-12 12:57 UTC, Conan-Kudo commented
@tiran So why attribute and not groups?

2020-05-12 13:00 UTC, tiran requested changes

2020-05-12 13:00 UTC, tiran commented on updates/99-fas.update
> -remove:aci: (targetattr = "nsAccountLock || fasTimezone || fasLocale || fasIRCNick || fasGPGKeyId || fasCreationTime || fasStatusNote")(targetfilter = "(objectclass=fasuser)")(version 3.0;acl "Read F
You have to keep the old removes to support migration from old plugin versions.

2020-05-12 13:00 UTC, tiran commented on updates/99-fas.update
> +add:aci: (targetattr = "fasTimezone || fasLocale || fasIRCNick || fasGPGKeyId || fasRHBZEmail || fasGitHubUsername || fasGitLabUsername || fasUserAgreements")(version 3.0;acl "Users can modify their
Is it a good idea to allow users to modify the attribute without checks? This allows a user to drop an agreement or add custom agreements, too.

2020-05-12 13:20 UTC, tiran commented
> @tiran So why attribute and not groups?

Why do you insist on groups? I was under the impression that agreement groups in old FAS were a workaround to simplify implementation, not an inherit design feature.

A separate attribute allows for different access rights.

2020-05-12 13:33 UTC, Conan-Kudo commented
@tiran Mainly because I wanted to know and I didn't know the background for the groups from before.

2020-05-12 13:40 UTC, tiran commented
> @tiran Mainly because I wanted to know and I didn't know the background for the groups from before.

That's always a good reason to ask :+1:

IMO it's a good idea to treat agreements and groups differently. FAS does not allow users to join a group easily but allows users to leave a group on request. Agreements should work the other way around or allow for more fine-grained access control. I proposed a solution that is more complex but allows for more control in the ticket.

2020-05-13 08:43 UTC, ryanlerch commented
@tiran yeah, the more complex solution is a go in my book.

closing this PR

2020-05-13 08:43 UTC, closed without merging