Make fasWebsiteURL attribute multi-valued
fedora-infra/freeipa-fas pull request #152
Opened 2024-06-06 17:32 UTC by phsmoura

Related issue: #151

2024-06-06 18:15 UTC, abompard requested changes
You'll also need to edit `updates/89-fas.update`

2024-06-13 16:56 UTC, abompard commented
Adding the index is good, thanks. I thought it would be necessary to add some sort of migration to change a SINGLE-VALUE attribute to multi-valued, but now I'm not sure. Would you know that, @tiran ?

2024-06-18 02:41 UTC, phsmoura commented
> Adding the index is good, thanks. I thought it would be necessary to add some sort of migration to change a SINGLE-VALUE attribute to multi-valued, but now I'm not sure. Would you know that, @tiran ?

OK, just did a few changes. Its possible now to add multiple lines in Blog and RSS fields. Im going to update the draft PR in Noggin that relate with this one

2024-06-18 11:19 UTC, abompard approved these changes

2024-06-18 11:19 UTC, merged